<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>e9520f00-ca57-4adc-855d-6ed040db7cc5</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>.</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.18"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Poker.Common\Poker.Common.csproj"/>
        <ProjectReference Include="..\Modules\Game\Poker.Game.Infrastructure\Poker.Game.Infrastructure.csproj"/>
        <ProjectReference Include="..\Modules\Game\Poker.Game.Presentation\Poker.Game.Presentation.csproj"/>
    </ItemGroup>

</Project>
