<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="MediatR">
        <HintPath>..\..\..\..\..\..\..\..\.nuget\packages\mediatr\12.5.0\lib\net6.0\MediatR.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Poker.Game.Application\Poker.Game.Application.csproj" />
      <ProjectReference Include="..\Poker.Game.Infrastructure\Poker.Game.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\" />
    </ItemGroup>

</Project>
