// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poker.Game.Infrastructure.Features.DBContexts;

#nullable disable

namespace Poker.Game.Infrastructure.Features.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250806075753_isDisconnected")]
    partial class isDisconnected
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tables")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poker.Game.Domain.Entities.Lobby", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HostingPlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hosting_player_id");

                    b.HasKey("Id")
                        .HasName("pk_lobbies");

                    b.ToTable("lobbies", "tables");
                });

            modelBuilder.Entity("Poker.Game.Domain.Entities.TableAggregate.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Balance")
                        .HasColumnType("integer")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer")
                        .HasColumnName("games_won");

                    b.Property<bool>("IsDisconnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disconnected");

                    b.Property<string>("LobbyId")
                        .HasColumnType("text")
                        .HasColumnName("lobby_id");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("numeric")
                        .HasColumnName("total_earnings");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("LobbyId")
                        .HasDatabaseName("ix_players_lobby_id");

                    b.ToTable("players", "tables");
                });

            modelBuilder.Entity("Poker.Game.Infrastructure.Features.Snapshots.TableSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TableJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TableJson");

                    b.HasKey("Id")
                        .HasName("pk_table_snapshots");

                    b.ToTable("table_snapshots", "tables");
                });

            modelBuilder.Entity("Poker.Game.Domain.Entities.TableAggregate.Player", b =>
                {
                    b.HasOne("Poker.Game.Domain.Entities.Lobby", null)
                        .WithMany("Players")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_players_lobbies_lobby_id");
                });

            modelBuilder.Entity("Poker.Game.Domain.Entities.Lobby", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
